name: json_canvas
description: A package that implemnents the JSON Canvas spec
version: 1.0.0
repository: https://github.com/jg-l/json_canvas

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
